// const fs=require('fs');
// console.log(Object.keys(fs).length);


// //fs.writeFileSync('notes.txt',`This File is generated by Node.JS.\nI am Keval Kankrecha.`);

// fs.appendFileSync
// ('notes.txt',`\nI am from Gondal.`);

//--
// const data=require('./utils.js');
// console.log(`${data.name}`);
//!--

//--
// const MathsFunction=require('./MatheMetialFunctions.js');
// console.log(MathsFunction.addition(1,2));
// console.log(MathsFunction.subtraction(5,2));
// console.log(MathsFunction.multiplication(5,2));
// console.log(MathsFunction.division(9,2));
// console.log(MathsFunction.modulo(10,2));
//!--


//--validator
// const validator=require('validator');
// console.log(validator.isEmail('keval@keval.abh'));
//!--

//--chalk
// const chalk=require('chalk');
// console.log(chalk.red("Remote Bhai"));
// console.log(chalk.red.bgRed.bold('Chhagan Chhatri'));
// console.log(chalk.red.bgBlack('Kem cho'),chalk.bgBlue('@Bhai'));
// console.log(chalk.bgGreen.bold('Jay Shree Ram'));
//!--

//to use nodemon write nodemon node app.js


